services:
  gateway-service:
    build: ./gateway
    env_file: 
      - .env
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - file_encryption_network

  database:
    image: mysql:9.3.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - file_encryption_data:/var/lib/mysql
    networks:
      - file_encryption_network

networks:
  file_encryption_network:

volumes:
  file_encryption_data:
